name: demo
on:
  push:
    branches:
      - 'pipeline-dev'
env:
  COMMIT_ID: 5a47159a4e5a468cce7dc3ec83b9dc169a657c83

jobs:
  conditional_step:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        repository: kmohit520/java-hello-world-with-gradle
    - run: cd /home/runner/work/test-actions/test-actions
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew build
    - run: cd build/libs
    - run: ls
    - run: java -jar build/libs/jb-hello-world-0.1.0.jar
